/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./Sınıf.glb
*/

import React, { useRef, useEffect, useState } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import { useGLTF, useScroll, SpotLight, Html } from '@react-three/drei'
import { Group, SpotLight as SL, Object3D } from 'three'

import Sinusoid from './sinusoid';


const SchoolClass = ({ cubeMoveRef, runAnims }: any) => {

    const [sinVisible, setSinVisible] = useState(false);

    const HtmlTest = () => {
    
        const { gl }: any = useThree();
      
        return(
            <Html transform portal={{ current: gl.domElement.parentNode }} 
                scale={[0.2, 0.2, 0.2]}
                rotation={[0, 0 ,0]}
                position={[0.55, 2.25, -5.2]}
            >
                {sinVisible && <Sinusoid />}
            </Html>
        )
    }

    const [lamp]  = useState(() => new Object3D());
    const [lamp2] = useState(() => new Object3D());
    const [lamp3] = useState(() => new Object3D());

    const ref = useRef<Group>(null!);
    const lampRef = useRef<SL>(null!);

    const data = useScroll();

    const breakPoint: number[] = [0.3, 0.4, 0.5, 0.55, 0.75];
    var blink = 0;

    useFrame((state, delta) => {

        blink += delta;
        if(blink > 3){
            blink = 0;
            if(!lampRef.current.visible) lampRef.current.visible = true;
        }
        else if(blink > 2){
            if(lampRef.current.visible) lampRef.current.visible = false;
            if(Math.random() > 0.8) lampRef.current.visible = true;
        }


        if(data.offset <= breakPoint[0]){
            if(ref.current.rotation.y !== -data.offset * 6 * Math.PI)
                ref.current.rotation.y = -data.offset * 6 * Math.PI;
            if(sinVisible && data.offset < 0.23) setSinVisible(false);

            if(runAnims[0][1].current && data.offset < 0.03){
                runAnims[0][0].start('middle');
                runAnims[0][1].current = false;
            }
            else if(!runAnims[0][1].current && data.offset > 0.04){
                runAnims[0][0].start('out');
                runAnims[0][1].current = true;
            }

            if(runAnims[1][1].current && data.offset < 0.05){
                runAnims[1][0].start('in');
                runAnims[1][1].current = false;
            }            
            else if(!runAnims[1][1].current && data.offset > 0.06 && data.offset < 0.15){
                runAnims[1][0].start('middle');
                runAnims[1][1].current = true;
            }
            else if(runAnims[1][1].current && data.offset > 0.16){
                runAnims[1][0].start('out');
                runAnims[1][1].current = false;
            }
        }
        else if(data.offset <= breakPoint[1]){
            if(ref.current.rotation.y !== -data.offset * 6 * Math.PI - (Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) - 1) * Math.PI * 0.4)
                ref.current.rotation.y = -data.offset * 6 * Math.PI - (Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) - 1) * Math.PI * 0.4;
            if(ref.current.position.z !== -Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) * 7 + 7)
                ref.current.position.z = -Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) * 7 + 7;
            if(state.camera.position.y !== 5 + Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) * 1.2 - 1.2)
                state.camera.position.y = 5 + Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) * 1.2 - 1.2;
        }
        else if(data.offset <= breakPoint[2]){
            if(ref.current.position.z !== -Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) * 7 + 7)
                ref.current.position.z = -Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) * 7 + 7;
            if(state.camera.position.y !== 5 + Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) * 1.2 - 1.2)
                state.camera.position.y = 5 + Math.sin((data.offset - breakPoint[0]) * 5 * Math.PI + Math.PI/2) * 1.2 - 1.2;
            if(ref.current.rotation.y !== 2* Math.PI)
                ref.current.rotation.y = 2 * Math.PI;
            if(!sinVisible) setSinVisible(true);
        }
        else if(data.offset <= breakPoint[3]){
            if(ref.current.position.z !== -Math.sin(Math.PI + Math.PI/2) * 7 + 7)
                ref.current.position.z = -Math.sin(Math.PI + Math.PI/2) * 7 + 7;
            if(state.camera.position.y !== 5 + Math.sin(Math.PI + Math.PI/2) * 1.2 - 1.2)
                state.camera.position.y = 5 + Math.sin(Math.PI + Math.PI/2) * 1.2 - 1.2;
            if(ref.current.position.y !== 0)
                ref.current.position.y = 0;
            if(!sinVisible) setSinVisible(true);
        }
        else{
            if(ref.current.position.y !== Math.sin((data.offset - breakPoint[3]) * 5 * Math.PI + Math.PI/2) * 5 - 5 && data.offset <= breakPoint[4])
                ref.current.position.y = Math.sin((data.offset - breakPoint[3]) * 5 * Math.PI + Math.PI/2) * 5 - 5;
            if(sinVisible && data.offset > 0.73) setSinVisible(false);
            if(!sinVisible && data.offset < 0.7) setSinVisible(true);
            
            if(!cubeMoveRef.current.visible && data.offset > 0.61) cubeMoveRef.current.visible = true;
            else if(cubeMoveRef.current.visible && data.offset < 0.6) cubeMoveRef.current.visible = false;

            if(runAnims[2][1].current && data.offset < 0.75){
                runAnims[2][0].start('in')
                runAnims[2][1].current = false;
            }
            else if(!runAnims[2][1].current && data.offset > 0.76 && data.offset < 0.87){
                runAnims[2][0].start('middle');
                runAnims[2][1].current = true;
            }
            else if(runAnims[2][1].current && data.offset > 0.88){
                runAnims[2][0].start('out');
                runAnims[2][1].current = false;
            }

            if(runAnims[3][1].current && data.offset < 0.79){
                runAnims[3][0].start('in')
                runAnims[3][1].current = false;
            }
            else if(!runAnims[3][1].current && data.offset > 0.8 && data.offset < 0.88){
                runAnims[3][0].start('middle');
                runAnims[3][1].current = true;
            }
            else if(runAnims[3][1].current && data.offset > 0.89){
                runAnims[3][0].start('out');
                runAnims[3][1].current = false;
            }

            if(!runAnims[4][1].current && data.offset < 0.95){
                runAnims[4][0].start('in')
                runAnims[4][1].current = true;
            }
            else if(runAnims[4][1].current && data.offset > 0.96){
                runAnims[4][0].start('middle');
                runAnims[4][1].current = false;
            }
        }
        // else{

            // if(cubeMoveRef.current.position.y !== (data.offset - breakPoint[4]) * 45)
            //     cubeMoveRef.current.position.y = (data.offset - breakPoint[4]) * 45;
        // }

        // if (ref.current.rotation.y !== -data.offset * 8 * Math.PI && data.offset <= breakPoint[0]){
        //     ref.current.rotation.y = -data.offset * 8 * Math.PI;
        // }
        // if(ref.current.position.z !== Math.sin((data.offset - breakPoint[0] + 0.05) * 5) * 14 && data.offset + 0.05 > breakPoint[0] && data.offset <= breakPoint[1]){
        //     if(ref.current.rotation.y !== breakPoint[0] * 8 * Math.PI && data.offset > breakPoint[0]) ref.current.rotation.y = breakPoint[0] * 8 * Math.PI;

        //     ref.current.position.z = Math.sin((data.offset - breakPoint[0] + 0.05) * 5) * 15;
        //     ref.current.position.y = Math.sin((data.offset - breakPoint[0] + 0.05) * 1.8 * Math.PI) * 3;
        //     ref.current.rotation.x = -0.25 * Math.sin((data.offset - breakPoint[0] + 0.05) * 1.8 * Math.PI);
        // }
        // if(data.offset - 0.05 > breakPoint[1] && data.offset <= breakPoint[2]){
        //     ref.current.position.y = - Math.sin(data.offset - breakPoint[1]) * 10 + 4
        // }
    });


    const { nodes, materials }: any = useGLTF('/SchoolClass.glb');
    return (
        <group dispose={null} ref={ref}>
            <SpotLight ref={lampRef}
                position={[-2, 5, -3]}
                angle={0.4}
                intensity={0.7}
                castShadow
                target={lamp}
            />
            {/* <SpotLight
                // distance={4}
                // anglePower={20}
                attenuation={2}
                position={[0.5, 5, -3]}
                angle={0.5}
                intensity={0}
                castShadow
                target={lamp2}
            /> */}
            {/* <SpotLight
                position={[-2, 5, 3]}
                angle={0.4}
                intensity={0.7}
                castShadow
                target={lamp3}
            /> */}
            <primitive object={lamp}  position={[-2, 0, -3]} />
            <primitive object={lamp2} position={[0.5, 2.5, -5]} />
            <primitive object={lamp3} position={[-2, 0, 3]} />

            <HtmlTest />

            <group position={[-4.02, 1.22, -4.87]} scale={[0.39, 0.04, 0.42]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube722.geometry} material={materials['Material.027']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube722_1.geometry} material={materials['Material.012']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube722_2.geometry} material={materials['Material.027']} />
            </group>
            <group position={[3.35, 1.08, 4.88]} rotation={[Math.PI / 2, 0, 3.09]} scale={[1.36, 0.03, 0.2]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube721.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube721_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[-3.31, 1.08, 4.82]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.36, 0.03, 0.2]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube720.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube720_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[0.07, 1.08, 4.83]} rotation={[Math.PI / 2, 0, -3.14]} scale={[1.36, 0.03, 0.2]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube719.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube719_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[0.07, 1.08, 3.13]} rotation={[Math.PI / 2, 0, -3.12]} scale={[1.36, 0.03, 0.2]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube718.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube718_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[-3.31, 1.08, 3.07]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.36, 0.03, 0.2]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube717.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube717_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[3.35, 1.08, 3.13]} rotation={[Math.PI / 2, 0, -3.12]} scale={[1.36, 0.03, 0.2]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube716.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube716_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[3.35, 1.08, 1.1]} rotation={[Math.PI / 2, 0, -3.06]} scale={[1.36, 0.03, 0.2]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube715.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube715_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[-3.31, 1.08, 1.12]} rotation={[Math.PI / 2, 0, 3.11]} scale={[1.36, 0.03, 0.2]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube714.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube714_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[0.07, 1.08, 1]} rotation={[Math.PI / 2, 0, 3.01]} scale={[1.36, 0.03, 0.2]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube711.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube711_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[5.07, 2.57, -1.02]} rotation={[0, -Math.PI / 2, 0]} scale={[1.11, 0.02, 0.04]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube703.geometry} material={materials['Material.012']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube703_1.geometry} material={materials['Material.007']} />
            </group>
            <group position={[-3.31, 1.35, 3.65]} scale={[1.37, 0.04, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube701.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube701_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[3.33, 1.35, 3.65]} scale={[1.37, 0.04, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube700.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube700_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[0.06, 1.35, 3.65]} scale={[1.37, 0.04, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube699.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube699_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[0.06, 1.35, 1.74]} scale={[1.37, 0.04, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube698.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube698_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[3.33, 1.35, 1.74]} scale={[1.37, 0.04, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube697.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube697_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[-3.31, 1.35, 1.74]} scale={[1.37, 0.04, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube696.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube696_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[-3.31, 1.35, -0.14]} scale={[1.37, 0.04, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube695.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube695_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[3.33, 1.35, -0.14]} scale={[1.37, 0.04, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube694.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube694_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[0.06, 1.35, -0.14]} scale={[1.37, 0.04, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube689.geometry} material={materials['Material.009']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube689_1.geometry} material={materials['Material.019']} />
            </group>
            <mesh castShadow receiveShadow geometry={nodes.Icosphere010.geometry} material={nodes.Icosphere010.material} position={[4.53, 0.49, -5.02]} rotation={[-0.91, -0.68, -2.51]} scale={0.07} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere009.geometry} material={materials['Material.028']} position={[4.68, 0.57, -4.97]} rotation={[-0.44, -0.75, -1.65]} scale={0.07} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere008.geometry} material={materials['Material.028']} position={[4.68, 0.59, -4.8]} rotation={[-0.44, -0.75, -1.65]} scale={0.08} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere007.geometry} material={materials['Material.028']} position={[4.59, 0.59, -4.88]} rotation={[-0.44, -0.75, -1.65]} scale={0.08} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere006.geometry} material={materials['Material.028']} position={[4.39, 0.65, -4.87]} scale={0.08} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere005.geometry} material={materials['Material.028']} position={[4.53, 0.71, -4.89]} rotation={[0.03, -0.29, -0.44]} scale={0.08} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere004.geometry} material={materials['Material.028']} position={[4.48, 0.66, -4.79]} scale={0.08} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere003.geometry} material={materials['Material.028']} position={[4.6, 0.63, -4.76]} rotation={[-0.49, 0.42, 1.12]} scale={0.08} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere002.geometry} material={materials['Material.028']} position={[4.68, 0.63, -4.88]} rotation={[-0.44, -0.75, -1.65]} scale={0.08} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere001.geometry} material={materials['Material.028']} position={[4.6, 0.63, -5]} rotation={[-0.91, -0.68, -2.51]} scale={0.09} />
            <mesh castShadow receiveShadow geometry={nodes.Icosphere.geometry} material={materials['Material.028']} position={[4.47, 0.63, -5]} rotation={[0.03, -0.29, -0.44]} scale={0.08} />
            <mesh castShadow receiveShadow geometry={nodes.Circle006.geometry} material={materials['Material.001']} position={[4.55, 0.69, -4.9]} scale={0.24} />
            <group position={[-3.71, 0.79, -3.49]} rotation={[0, 0.37, 0]} scale={[0.38, 0.06, 0.45]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube650.geometry} material={materials['Material.005']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube650_1.geometry} material={materials['Material.019']} />
            </group>
            <group position={[-2.37, 1.27, -2.52]} rotation={[0, Math.PI / 2, 0]} scale={[0.32, 0.11, 0.15]}>
                <mesh castShadow receiveShadow geometry={nodes.Plane015.geometry} material={materials['Material.028']} />
                <mesh castShadow receiveShadow geometry={nodes.Plane015_1.geometry} material={materials['Material.029']} />
                <mesh castShadow receiveShadow geometry={nodes.Plane015_2.geometry} material={materials['Material.010']} />
            </group>
            <mesh castShadow receiveShadow geometry={nodes.Cube591.geometry} material={materials['Material.027']} position={[-2.81, 0.74, -2.46]} rotation={[0, -Math.PI / 2, 0]} scale={[0.73, 0.53, 1.33]}>
                <mesh castShadow receiveShadow geometry={nodes.Circle002_2.geometry} material={materials['Material.019']} position={[-0.82, -1.14, 0.93]} scale={[0.1, 0.13, 0.06]} />
                <mesh castShadow receiveShadow geometry={nodes.Circle003_2.geometry} material={materials['Material.019']} position={[0.99, -1.14, 0.93]} scale={[0.1, 0.13, 0.06]} />
                <mesh castShadow receiveShadow geometry={nodes.Circle004.geometry} material={materials['Material.019']} position={[0.99, -1.14, -0.92]} scale={[0.1, 0.13, 0.06]} />
                <mesh castShadow receiveShadow geometry={nodes.Circle005.geometry} material={materials['Material.019']} position={[-0.82, -1.14, -0.92]} scale={[0.1, 0.13, 0.06]} />
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.Plane006.geometry} material={materials.Material} position={[-3.48, 1.3, -2.24]} rotation={[-2.28, 1.05, 2.51]} scale={[0.18, 0.37, 0.18]} />
            <group position={[2.21, 1.03, -5.29]} rotation={[0, Math.PI / 2, 0]} scale={[0.07, 0.06, 0.08]}>
                <mesh castShadow receiveShadow geometry={nodes.Circle002.geometry} material={materials['Material.016']} />
                <mesh castShadow receiveShadow geometry={nodes.Circle002_1.geometry} material={materials['Material.017']} />
            </group>
            <group position={[4.97, 1.75, -3.28]} rotation={[Math.PI, 0, 1.59]} scale={[1.76, 0.44, 0.88]}>
                <mesh castShadow receiveShadow geometry={nodes.Plane006_1.geometry} material={materials['Material.006']} />
                <mesh castShadow receiveShadow geometry={nodes.Plane006_2.geometry} material={materials['Material.007']} />
                <mesh castShadow receiveShadow geometry={nodes.Plane006_3.geometry} material={materials['Material.008']} />
            </group>
            <mesh castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials.Material} position={[-0.15, 0.1, -0.14]} scale={5.25} />
            <group position={[0.56, 2.25, -5.38]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.15, 0.54, 2.13]}>
                <mesh castShadow receiveShadow geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
                <mesh castShadow receiveShadow geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube196_1.geometry} material={materials['Material.001']} position={[1.1, 0.21, -0.77]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.11, 0.01, 0.18]} />

                {/* <HtmlTest /> */}

            </group>
            <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['Material.004']} position={[-0.35, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['Material.004']} position={[-0.35, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Material.004']} position={[-0.35, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials['Material.004']} position={[-0.35, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials['Material.004']} position={[-0.35, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials['Material.004']} position={[-0.35, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials['Material.004']} position={[-0.35, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials['Material.004']} position={[-0.35, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials['Material.004']} position={[-0.35, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube009.geometry} material={materials['Material.004']} position={[-0.35, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube010.geometry} material={materials['Material.004']} position={[-0.35, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials['Material.004']} position={[-0.35, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials['Material.004']} position={[-0.35, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials['Material.004']} position={[-0.35, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube014.geometry} material={materials['Material.004']} position={[-1.07, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube015.geometry} material={materials['Material.004']} position={[-1.07, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials['Material.004']} position={[-1.07, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube017.geometry} material={materials['Material.004']} position={[-1.07, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube018.geometry} material={materials['Material.004']} position={[-1.07, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube019.geometry} material={materials['Material.004']} position={[-1.07, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube020.geometry} material={materials['Material.004']} position={[-1.07, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube021.geometry} material={materials['Material.004']} position={[-1.07, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube022.geometry} material={materials['Material.004']} position={[-1.07, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube023.geometry} material={materials['Material.004']} position={[-1.07, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube024.geometry} material={materials['Material.004']} position={[-1.07, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube025.geometry} material={materials['Material.004']} position={[-1.07, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube026.geometry} material={materials['Material.004']} position={[-1.07, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube027.geometry} material={materials['Material.004']} position={[-1.07, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube028.geometry} material={materials['Material.004']} position={[-1.79, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube029.geometry} material={materials['Material.004']} position={[-1.79, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube030.geometry} material={materials['Material.004']} position={[-1.79, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube031.geometry} material={materials['Material.004']} position={[-1.79, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube032.geometry} material={materials['Material.004']} position={[-1.79, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube033.geometry} material={materials['Material.004']} position={[-1.79, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube034.geometry} material={materials['Material.004']} position={[-1.79, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube035.geometry} material={materials['Material.004']} position={[-1.79, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube036.geometry} material={materials['Material.004']} position={[-1.79, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube037.geometry} material={materials['Material.004']} position={[-1.79, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube038.geometry} material={materials['Material.004']} position={[-1.79, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube039.geometry} material={materials['Material.004']} position={[-1.79, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube040.geometry} material={materials['Material.004']} position={[-1.79, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube041.geometry} material={materials['Material.004']} position={[-1.79, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube042.geometry} material={materials['Material.004']} position={[-2.51, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube043.geometry} material={materials['Material.004']} position={[-2.51, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube044.geometry} material={materials['Material.004']} position={[-2.51, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube045.geometry} material={materials['Material.004']} position={[-2.51, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube046.geometry} material={materials['Material.004']} position={[-2.51, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube047.geometry} material={materials['Material.004']} position={[-2.51, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube048.geometry} material={materials['Material.004']} position={[-2.51, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube049.geometry} material={materials['Material.004']} position={[-2.51, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube050.geometry} material={materials['Material.004']} position={[-2.51, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube051.geometry} material={materials['Material.004']} position={[-2.51, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube052.geometry} material={materials['Material.004']} position={[-2.51, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials['Material.004']} position={[-2.51, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube054.geometry} material={materials['Material.004']} position={[-2.51, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube055.geometry} material={materials['Material.004']} position={[-2.51, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube056.geometry} material={materials['Material.004']} position={[-3.24, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube057.geometry} material={materials['Material.004']} position={[-3.24, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube058.geometry} material={materials['Material.004']} position={[-3.24, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube059.geometry} material={materials['Material.004']} position={[-3.24, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube060.geometry} material={materials['Material.004']} position={[-3.24, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube061.geometry} material={materials['Material.004']} position={[-3.24, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube062.geometry} material={materials['Material.004']} position={[-3.24, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube063.geometry} material={materials['Material.004']} position={[-3.24, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube064.geometry} material={materials['Material.004']} position={[-3.24, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube065.geometry} material={materials['Material.004']} position={[-3.24, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube066.geometry} material={materials['Material.004']} position={[-3.24, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube067.geometry} material={materials['Material.004']} position={[-3.24, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube068.geometry} material={materials['Material.004']} position={[-3.24, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube069.geometry} material={materials['Material.004']} position={[-3.24, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube070.geometry} material={materials['Material.004']} position={[-3.96, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube071.geometry} material={materials['Material.004']} position={[-3.96, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube072.geometry} material={materials['Material.004']} position={[-3.96, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube073.geometry} material={materials['Material.004']} position={[-3.96, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube074.geometry} material={materials['Material.004']} position={[-3.96, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube075.geometry} material={materials['Material.004']} position={[-3.96, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube076.geometry} material={materials['Material.004']} position={[-3.96, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube077.geometry} material={materials['Material.004']} position={[-3.96, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube078.geometry} material={materials['Material.004']} position={[-3.96, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube079.geometry} material={materials['Material.004']} position={[-3.96, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube080.geometry} material={materials['Material.004']} position={[-3.96, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube081.geometry} material={materials['Material.004']} position={[-3.96, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube082.geometry} material={materials['Material.004']} position={[-3.96, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube083.geometry} material={materials['Material.004']} position={[-3.96, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube084.geometry} material={materials['Material.004']} position={[-4.68, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials['Material.004']} position={[-4.68, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube086.geometry} material={materials['Material.004']} position={[-4.68, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube087.geometry} material={materials['Material.004']} position={[-4.68, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube088.geometry} material={materials['Material.004']} position={[-4.68, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube089.geometry} material={materials['Material.004']} position={[-4.68, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube090.geometry} material={materials['Material.004']} position={[-4.68, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube091.geometry} material={materials['Material.004']} position={[-4.68, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube092.geometry} material={materials['Material.004']} position={[-4.68, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube093.geometry} material={materials['Material.004']} position={[-4.68, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube094.geometry} material={materials['Material.004']} position={[-4.68, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube095.geometry} material={materials['Material.004']} position={[-4.68, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube096.geometry} material={materials['Material.004']} position={[-4.68, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube097.geometry} material={materials['Material.004']} position={[-4.68, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube098.geometry} material={materials['Material.004']} position={[0.38, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube099.geometry} material={materials['Material.004']} position={[0.38, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube100.geometry} material={materials['Material.004']} position={[0.38, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube101.geometry} material={materials['Material.004']} position={[0.38, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube102.geometry} material={materials['Material.004']} position={[0.38, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube103.geometry} material={materials['Material.004']} position={[0.38, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube104.geometry} material={materials['Material.004']} position={[0.38, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube105.geometry} material={materials['Material.004']} position={[0.38, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube106.geometry} material={materials['Material.004']} position={[0.38, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube107.geometry} material={materials['Material.004']} position={[0.38, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube108.geometry} material={materials['Material.004']} position={[0.38, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube109.geometry} material={materials['Material.004']} position={[0.38, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube110.geometry} material={materials['Material.004']} position={[0.38, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube111.geometry} material={materials['Material.004']} position={[0.38, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube112.geometry} material={materials['Material.004']} position={[1.1, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube113.geometry} material={materials['Material.004']} position={[1.1, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube114.geometry} material={materials['Material.004']} position={[1.1, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube115.geometry} material={materials['Material.004']} position={[1.1, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube116.geometry} material={materials['Material.004']} position={[1.1, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube117.geometry} material={materials['Material.004']} position={[1.1, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube118.geometry} material={materials['Material.004']} position={[1.1, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube119.geometry} material={materials['Material.004']} position={[1.1, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube120.geometry} material={materials['Material.004']} position={[1.1, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube121.geometry} material={materials['Material.004']} position={[1.1, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube122.geometry} material={materials['Material.004']} position={[1.1, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube123.geometry} material={materials['Material.004']} position={[1.1, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube124.geometry} material={materials['Material.004']} position={[1.1, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube125.geometry} material={materials['Material.004']} position={[1.1, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube126.geometry} material={materials['Material.004']} position={[1.82, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube127.geometry} material={materials['Material.004']} position={[1.82, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube128.geometry} material={materials['Material.004']} position={[1.82, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube129.geometry} material={materials['Material.004']} position={[1.82, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube130.geometry} material={materials['Material.004']} position={[1.82, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube131.geometry} material={materials['Material.004']} position={[1.82, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube132.geometry} material={materials['Material.004']} position={[1.82, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube133.geometry} material={materials['Material.004']} position={[1.82, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube134.geometry} material={materials['Material.004']} position={[1.82, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube135.geometry} material={materials['Material.004']} position={[1.82, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube136.geometry} material={materials['Material.004']} position={[1.82, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube137.geometry} material={materials['Material.004']} position={[1.82, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube138.geometry} material={materials['Material.004']} position={[1.82, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube139.geometry} material={materials['Material.004']} position={[1.82, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube140.geometry} material={materials['Material.004']} position={[2.54, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube141.geometry} material={materials['Material.004']} position={[2.54, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube142.geometry} material={materials['Material.004']} position={[2.54, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube143.geometry} material={materials['Material.004']} position={[2.54, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube144.geometry} material={materials['Material.004']} position={[2.54, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube145.geometry} material={materials['Material.004']} position={[2.54, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube146.geometry} material={materials['Material.004']} position={[2.54, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube147.geometry} material={materials['Material.004']} position={[2.54, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube148.geometry} material={materials['Material.004']} position={[2.54, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube149.geometry} material={materials['Material.004']} position={[2.54, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube150.geometry} material={materials['Material.004']} position={[2.54, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube151.geometry} material={materials['Material.004']} position={[2.54, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube152.geometry} material={materials['Material.004']} position={[2.54, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube153.geometry} material={materials['Material.004']} position={[2.54, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube154.geometry} material={materials['Material.004']} position={[3.27, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube155.geometry} material={materials['Material.004']} position={[3.27, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube156.geometry} material={materials['Material.004']} position={[3.27, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube157.geometry} material={materials['Material.004']} position={[3.27, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube158.geometry} material={materials['Material.004']} position={[3.27, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube159.geometry} material={materials['Material.004']} position={[3.27, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube160.geometry} material={materials['Material.004']} position={[3.27, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube161.geometry} material={materials['Material.004']} position={[3.27, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube162.geometry} material={materials['Material.004']} position={[3.27, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube163.geometry} material={materials['Material.004']} position={[3.27, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube164.geometry} material={materials['Material.004']} position={[3.27, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube165.geometry} material={materials['Material.004']} position={[3.27, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube166.geometry} material={materials['Material.004']} position={[3.27, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube167.geometry} material={materials['Material.004']} position={[3.27, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube168.geometry} material={materials['Material.004']} position={[3.99, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube169.geometry} material={materials['Material.004']} position={[3.99, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube170.geometry} material={materials['Material.004']} position={[3.99, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube171.geometry} material={materials['Material.004']} position={[3.99, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube172.geometry} material={materials['Material.004']} position={[3.99, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube173.geometry} material={materials['Material.004']} position={[3.99, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube174.geometry} material={materials['Material.004']} position={[3.99, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube175.geometry} material={materials['Material.004']} position={[3.99, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube176.geometry} material={materials['Material.004']} position={[3.99, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube177.geometry} material={materials['Material.004']} position={[3.99, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube178.geometry} material={materials['Material.004']} position={[3.99, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube179.geometry} material={materials['Material.004']} position={[3.99, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube180.geometry} material={materials['Material.004']} position={[3.99, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube181.geometry} material={materials['Material.004']} position={[3.99, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube182.geometry} material={materials['Material.004']} position={[4.71, 0.07, 4.33]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube183.geometry} material={materials['Material.004']} position={[4.71, 0.07, 3.61]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube184.geometry} material={materials['Material.004']} position={[4.71, 0.07, 2.88]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube185.geometry} material={materials['Material.004']} position={[4.71, 0.07, 2.16]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube186.geometry} material={materials['Material.004']} position={[4.71, 0.07, 1.44]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube187.geometry} material={materials['Material.004']} position={[4.71, 0.07, 0.72]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube188.geometry} material={materials['Material.004']} position={[4.71, 0.07, -0.01]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube189.geometry} material={materials['Material.004']} position={[4.71, 0.07, -0.73]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube190.geometry} material={materials['Material.004']} position={[4.71, 0.07, -1.45]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube191.geometry} material={materials['Material.004']} position={[4.71, 0.07, -2.17]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube192.geometry} material={materials['Material.004']} position={[4.71, 0.07, -2.9]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube193.geometry} material={materials['Material.004']} position={[4.71, 0.07, -3.62]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube194.geometry} material={materials['Material.004']} position={[4.71, 0.07, -4.34]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube195.geometry} material={materials['Material.004']} position={[4.71, 0.07, -5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube611.geometry} material={materials['Material.004']} position={[4.71, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube612.geometry} material={materials['Material.004']} position={[3.99, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube613.geometry} material={materials['Material.004']} position={[3.27, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube614.geometry} material={materials['Material.004']} position={[2.54, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube615.geometry} material={materials['Material.004']} position={[1.82, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube616.geometry} material={materials['Material.004']} position={[1.1, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube617.geometry} material={materials['Material.004']} position={[0.38, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube618.geometry} material={materials['Material.004']} position={[-4.68, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube619.geometry} material={materials['Material.004']} position={[-3.96, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube620.geometry} material={materials['Material.004']} position={[-3.24, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube621.geometry} material={materials['Material.004']} position={[-2.51, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube622.geometry} material={materials['Material.004']} position={[-1.79, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube623.geometry} material={materials['Material.004']} position={[-1.07, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
            <mesh castShadow receiveShadow geometry={nodes.Cube624.geometry} material={materials['Material.004']} position={[-0.35, 0.07, 5.06]} scale={[0.35, 0.08, 0.35]} />
        </group>
    )
}

useGLTF.preload('/SchoolClass.glb')





export default SchoolClass